name: Code linter 🎨
on: [push]
jobs:
  code-linter:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.0'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint:fix

      - name: Run format check
        run: npm run format
